language: python

python:
  - "3.5"
  - "3.6"

install:
  # get conda, python 3
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # add channels
  - conda config --append channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  # install JS dependencies
  - conda install -n test-environment yarn
  # install python testing dependencies
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  # invoke NPM building of JS dependencies
  #- python setup.py build_py

script:
  # Your test script goes here
  - pytest